<a href="https://colab.research.google.com/github/poorvitha02/Poorvitha-/blob/main/Assignment%20(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def matrix_multiply(A, B):
    """
    Perform matrix multiplication using numpy.

    Args:
        A (np.ndarray): First matrix of shape (m, n)
        B (np.ndarray): Second matrix of shape (n, p)

    Returns:
        np.ndarray: Resulting matrix of shape (m, p)
    """
    # Check if shapes are compatible
    if A.shape[1] != B.shape[0]:
        raise ValueError("Incompatible dimensions: A's columns must match B's rows")

    # Perform matrix multiplication
    result = np.dot(A, B)
    return result
 # Define two matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Call the function
C = matrix_multiply(A, B)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("A x B =\n", C)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
A x B =
 [[19 22]
 [43 50]]


In [2]:
import pandas as pd

# Sample data
data = {
    'Age': [20, 25, 30, 35, 40],
    'Salary': [30000, 40000, 50000, 60000, 70000]
}

df = pd.DataFrame(data)
print("Original Data:\n", df)

# Min-Max Scaling
min_max_scaled = (df - df.min()) / (df.max() - df.min())
print("\nMin-Max Scaled Data:\n", min_max_scaled)

# Standardization
standardized = (df - df.mean()) / df.std()
print("\nStandardized Data:\n", standardized)

Original Data:
    Age  Salary
0   20   30000
1   25   40000
2   30   50000
3   35   60000
4   40   70000

Min-Max Scaled Data:
     Age  Salary
0  0.00    0.00
1  0.25    0.25
2  0.50    0.50
3  0.75    0.75
4  1.00    1.00

Standardized Data:
         Age    Salary
0 -1.264911 -1.264911
1 -0.632456 -0.632456
2  0.000000  0.000000
3  0.632456  0.632456
4  1.264911  1.264911
